### ISSUE TITLE
Country borders are not rendered

### ISSUE THREAD

**Issue by OsamaShabrez** [SomeoneElseOSM/openstreetmap-carto-AJT#2]
I am following this guide here: https://wiki.openstreetmap.org/wiki/User:SomeoneElse/Ubuntu_1804_tileserver_load to create my own osm tile server. Everything works fine but the country boundaries are not rendered in my tiles. Here are a few examples:

![Europe zoom level 4:](https://i.imgur.com/q8H3qla.png)

![Germany border with Paris, Netherlands, Luxembourg etc.](https://i.imgur.com/BRhICdz.png)

I haven't changed anything in my project.mml and it correctly references the country boundaries from postgres.

```
$ cat project.mml | grep "administrative"

        "table": "(select way,admin_level\n       from planet_osm_roads\n       where \"boundary\"='administrative'\n         and admin_level in ('0','1','2','3','4')\n       ) as admin_01234",
        "table": "(select way,admin_level\n       from planet_osm_roads\n       where \"boundary\"='administrative'\n         and admin_level in ('5','6','7','8')\n       ) as admin_5678",
        "table": "(select way,admin_level\n       from planet_osm_roads\n       where \"boundary\"='administrative'\n         and admin_level in ('9', '10')\n       ) as admin_other",
        "table": "(select way, name, admin_level from planet_osm_polygon where \"boundary\" = 'administrative' and admin_level in ('0','1','2','3','4','5','6','7','8','9','10')) as admin_text",
```

but it does not reference `/data/ne_110m_admin_0_boundary_lines_land` directory files in `project.mml` file or in `mapnik.xml`. Is this the cause of this issue?

**Comment by matkoniecz** [comment]
> Everything works fine but the country boundaries are not rendered in my tiles. Here are a few examples:

Please, check is it working with a current version of this style. You are either using some alternative style or extremely old version (based on a road colour styling).

**Comment by SomeoneElseOSM** [comment]
> Everything works fine but the country boundaries are not rendered

Yes - that's by design.  This particular map style doesn't show administrative boundaries by default as part of the map tiles, although it's possible to add them on as an overlay afterwards.  

The actual bit that removes the admin boundaries is here: https://github.com/SomeoneElseOSM/SomeoneElse-style/blob/master/style.lua#L891 .

Removing admin boundaries means that purple is available as a colour for other features - different shades of it are used for long distance walking, cycling and horse-riding paths.  

If you want to show admin boundaries as an overlay, have a look at https://www.openstreetmap.org/user/SomeoneElse/diary/47007 which explains how I did it at https://map.atownsend.org.uk/maps/map/map.html .  If you'd like to have admin boundaries rendered as part of the map tiles, then comment out the lines in style.lua that remove them.

There are advantages and disadvantages of both methods.  An advantage of having boundaries in a separate layer is that you can choose whether or not to display them; a disadvantage is that label collisions between tile layers can occur (see examples noted in this diary comment: https://www.openstreetmap.org/user/SomeoneElse/diary/47007#comment43366 ).

**Comment by SomeoneElseOSM** [comment]
(and finally for completeness) https://wiki.openstreetmap.org/wiki/User:SomeoneElse/Ubuntu_1804_tileserver_load and https://switch2osm.org/manually-building-a-tile-server-18-04-lts/ are fairly similar, but use different map styles.  Both evolved from the same root (the "standard" style in use on openstreetmap.org a few years ago), but have different goals and different limitations.

If you'd like to have a map style that creates tiles that look exactly the same as you see on openstreetmap.org then you can just follow the switch2osm.org guide and that's what you'll get.  If you're creating a background map for something else then you'll probably want to make some features more or less visible, and modify the map style you use in some way - you can do that with either style (and with many others).
